use_frameworks!

platform :ios, '10.0'

source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

target 'SwiftRuntimeExample' do
  
  pod 'DYFRuntimeProvider'
  pod 'DYFSwiftRuntimeProvider'
  
  target 'SwiftRuntimeExample_Tests' do
    inherit! :search_paths
    
  end
end
